# Generated by Django 5.0.6 on 2024-06-01 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="about/")),
            ],
        ),
        migrations.CreateModel(
            name="Achivement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField()),
                ("image", models.FileField(upload_to="achivements/")),
            ],
            options={
                "verbose_name_plural": "Achivements",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("sub_title", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=180)),
                ("country_icon", models.FileField(upload_to="branches/")),
                ("name", models.CharField(max_length=180)),
                ("address", models.CharField(max_length=180)),
                ("number", models.CharField(max_length=180)),
                ("image", models.ImageField(upload_to="branches/")),
                ("hover_image", models.ImageField(upload_to="branches/")),
            ],
            options={
                "verbose_name_plural": "Branches",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="BranchTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("sub_title", models.CharField(max_length=180)),
            ],
            options={
                "verbose_name_plural": "Branch Title",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("image", models.ImageField(upload_to="clients/")),
            ],
            options={
                "verbose_name_plural": "Client Logos",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=180)),
                ("message", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Contact Details",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="ContactCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="conatct/")),
            ],
            options={
                "verbose_name_plural": "Contact Card",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="CuttingEdgeProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("image", models.ImageField(upload_to="cutting_edge_products/")),
            ],
            options={
                "verbose_name_plural": "Cutting Edge Products",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="CuttingEdgeProductTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("sub_title", models.CharField(max_length=180)),
            ],
            options={
                "verbose_name_plural": "Cutting Edge Product Title",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=180)),
                ("answer", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="FaqTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="faq/")),
                ("title", models.CharField(max_length=180)),
                ("sub_title", models.CharField(max_length=180)),
            ],
            options={
                "verbose_name_plural": "Faq title",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon_image", models.FileField(upload_to="features-icon/")),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Features",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="FeatureTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("sub_title", models.CharField(max_length=180)),
            ],
            options={
                "verbose_name_plural": "Feature Title",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="mission/")),
            ],
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Objective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField()),
                ("image", models.FileField(upload_to="objectives/")),
            ],
            options={
                "verbose_name_plural": "Objective",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField()),
                ("sub_title", models.CharField(blank=True, max_length=180, null=True)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="products/")),
                ("icon", models.FileField(upload_to="product_icon/")),
            ],
            options={
                "verbose_name_plural": "Products",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="ProductCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("sub_title", models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name="ProductTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("sub_title", models.CharField(max_length=180)),
            ],
            options={
                "verbose_name_plural": "Product title",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField()),
                ("image", models.FileField(upload_to="services/")),
            ],
        ),
        migrations.CreateModel(
            name="ServiceTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("sub_title", models.CharField(max_length=180)),
            ],
            options={
                "verbose_name_plural": "Service Title",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("position", models.CharField(max_length=180)),
                ("image", models.ImageField(upload_to="team/")),
            ],
            options={
                "verbose_name_plural": "Teams",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="TeamTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("sub_title", models.CharField(max_length=180)),
            ],
            options={
                "verbose_name_plural": "Team title",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("position", models.CharField(max_length=180)),
                ("image", models.ImageField(upload_to="testimonials/")),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TestimonialTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("sub_title", models.CharField(max_length=180)),
            ],
            options={
                "verbose_name_plural": "Testimonial Title",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Vision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("decsription", models.TextField()),
                ("image", models.ImageField(upload_to="vision/")),
            ],
        ),
        migrations.CreateModel(
            name="AboutFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature", models.CharField(max_length=180)),
                (
                    "about",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.about"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AchivementFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                (
                    "achivement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.achivement"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObjectiveFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                (
                    "objective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.objective"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=180, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductFeatureSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.FileField(
                        blank=True, null=True, upload_to="product_feature_icon/"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=180, null=True)),
                ("decsription", models.TextField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.product"
                    ),
                ),
            ],
        ),
    ]
