# Generated by Django 5.0.6 on 2024-06-01 06:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_product_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("order",), "verbose_name_plural": "Products"},
        ),
    ]
