# Generated by Django 5.0.6 on 2024-06-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="order",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
