# Generated by Django 5.0.6 on 2024-06-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_alter_service_options_service_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactAdress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("number", models.CharField(max_length=15)),
                ("location", models.CharField(max_length=100)),
            ],
        ),
    ]
