# Generated by Django 5.0.6 on 2024-06-01 07:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_contactadress"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactadress",
            old_name="location",
            new_name="place",
        ),
    ]
