# Generated by Django 5.0.6 on 2024-06-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_rename_location_contactadress_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("socail_media", models.CharField(max_length=180)),
                ("link", models.URLField()),
                ("icon", models.CharField(max_length=180)),
            ],
            options={
                "verbose_name_plural": "Social Media",
                "ordering": ("id",),
            },
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ("id",), "verbose_name_plural": "Contact Form"},
        ),
    ]
