# Generated by Django 5.0.6 on 2024-06-01 07:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_socialmedia_alter_contact_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="socialmedia",
            old_name="socail_media",
            new_name="social_media",
        ),
    ]
