# Generated by Django 5.0.6 on 2024-06-01 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0009_rename_socail_media_socialmedia_social_media"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="socialmedia",
            options={"ordering": ("id",), "verbose_name_plural": "Social Medias"},
        ),
        migrations.RenameField(
            model_name="productfeatureslide",
            old_name="decsription",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="productfeatureslide",
            old_name="icon",
            new_name="icon_image",
        ),
    ]
